### ISSUE TITLE
PKGBUILD does not build in clean chroot

### ISSUE THREAD

**Issue by xiota** [bartoszek/AUR-meshlab-git#4]
PKGBUILD from https://aur.archlinux.org/packages/meshlab-git fails to build in clean chroot.

[meshlab-git.log](https://github.com/bartoszek/AUR-meshlab-git/files/12594302/meshlab-git.log)

**Comment by bartoszek** [comment]
fixed in 9d404c27deb4aac94e0dc673c2fa59f5a872f566
